### ISSUE TITLE
Hello, could you please provide a usable visualization code for TSNE？

### ISSUE THREAD

**Issue by zhouzheng1123** [Hlings/AcroFOD#11]
Hello, could you please provide a usable visualization code for TSNE，I want to achieve the visualization effect of tsne in my paper。

**Comment by gaoypeng** [comment]
Hi! Sorry for the late reply :(. You can check my new updated repository [AsyFOD](https://github.com/Hlings/AsyFOD). I upload the t-SNE visualization code in the [file](https://github.com/Hlings/AsyFOD/blob/main/tsne_ins_layer9.py). I hope you find them helpful and welcome further discussions :).

**Comment by zhouzheng1123** [comment]
Thank you very much for the author's work. This is an amazing work, and I have recently developed two works based on it. Can the author provide more detailed instructions on how to use the TSNE code? Thank you again!

**Comment by gaoypeng** [comment]
The process is like the test.py, using a checkpoint and dataset config like the training, the command is very similar. Feel free to ask me any specific questions :)
