### ISSUE TITLE
数据集在哪啊，大佬请指教

### ISSUE THREAD

**Issue by usssr11** [Hlings/AcroFOD#13]
Readme中提到 “The above data has been uploaded. I will share the links this week.”。
是这周可以看到voc、coco数据集吗，另外想要一个联系方式可以吗。。。

**Comment by gaoypeng** [comment]
嗯嗯 我会release数据集放links上来，不过我论文中貌似没有PASCAL VOC？ 联系方式现在可以用邮箱联系我，gaoyp23@mail2.sysu.edu.cn

**Comment by gaoypeng** [comment]
数据已经更新了。（All the datasets used for training and validation have been updated.）
