### ISSUE TITLE
Domain-aware Augmentation

### ISSUE THREAD

**Issue by zhangyu619** [Hlings/AcroFOD#15]
Hello, recently read this paper you wrote and found it very helpful, want to understand your code, but I am a beginner some details do not read too well, please ask the paper's Domain-aware Augmentation and Directive Optimization Strategy in which part of the code embodied in the specific, thank you!

**Comment by gaoypeng** [comment]
For domain-aware augmentation, I first merge the source and target data into the same dataloader (see the yaml config file ). Then, I perform the augmentation [here](https://github.com/Hlings/AcroFOD/blob/e0583b44ed36e9c4778236a87f8c33a29fb84891/utils/datasets.py#L504C17-L504C17) for the image-level augmentation. The instance-level (copy-paste) augmentation can refer to the copy_paste_da.py file.

For the Optimization Strategy, I implement that before the epoch training, see [here](https://github.com/Hlings/AcroFOD/blob/e0583b44ed36e9c4778236a87f8c33a29fb84891/train_MMD.py#L292) (Lines 292-330 in the train.MMD.py)

I hope this reply finds you well :)

**Comment by zhangyu619** [comment]
感谢您的回复！我会回去仔细阅读的

**Comment by zhangyu619** [comment]
你好[Cityscapes_8cls_foggy](https://pan.baidu.com/s/1S1NuZSyailngL2M3STAZmA?pwd=y4yw)这个数据集分享好像过期了，能麻烦再分享一下吗，谢谢！

**Comment by gaoypeng** [comment]
Hi 我已经更新了一下链接，现在试一下可以了嘛？

**Comment by zhangyu619** [comment]
谢谢大佬，已经可以了

**Comment by zhangyu619** [comment]
还有个问题，我看您论文中C-F是将Cityscapes作为源域，Foggy version of Cityscapes作为目标域来训练的，但是我看您给的数据集的意思好像是将Foggy version of Cityscapes作为源域，从Cityscapes中取出8张图像来作为目标域训练，还有就是目标域选取图像有什么要求吗，假如我选的这8张图像不能包含所有的类别，这样会不会影响最后的效果，您能稍微给我解释一下吗，谢谢！

**Comment by gaoypeng** [comment]
Hi 可以参考这里的[回答](https://github.com/Hlings/AcroFOD/issues/14#issuecomment-1776635645)和这个issue

**Comment by zhangyu619** [comment]
感谢您的回复！

**Comment by rejghirs** [comment]
> For domain-aware augmentation, I first merge the source and target data into the same dataloader (see the yaml config file ). Then, I perform the augmentation [here](https://github.com/Hlings/AcroFOD/blob/e0583b44ed36e9c4778236a87f8c33a29fb84891/utils/datasets.py#L504C17-L504C17) for the image-level augmentation. The instance-level (copy-paste) augmentation can refer to the copy_paste_da.py file.
> 
> For the Optimization Strategy, I implement that before the epoch training, see [here](https://github.com/Hlings/AcroFOD/blob/e0583b44ed36e9c4778236a87f8c33a29fb84891/train_MMD.py#L292) (Lines 292-330 in the train.MMD.py)
> 
> I hope this reply finds you well :)



> For domain-aware augmentation, I first merge the source and target data into the same dataloader (see the yaml config file ). Then, I perform the augmentation [here](https://github.com/Hlings/AcroFOD/blob/e0583b44ed36e9c4778236a87f8c33a29fb84891/utils/datasets.py#L504C17-L504C17) for the image-level augmentation. The instance-level (copy-paste) augmentation can refer to the copy_paste_da.py file.
> 
> For the Optimization Strategy, I implement that before the epoch training, see [here](https://github.com/Hlings/AcroFOD/blob/e0583b44ed36e9c4778236a87f8c33a29fb84891/train_MMD.py#L292) (Lines 292-330 in the train.MMD.py)
> 
> I hope this reply finds you well :)

请问image-level的augmentation是在datasets.py的从第几行到第几行，可以再具体一点嘛,期待大佬回复~

**Comment by gaoypeng** [comment]
Hi datasets.py 中 Lines 504-507是mosaic 可以看那个load_mosaic的函数 Lines 510-514是 Mixup Lines 676-678是copy-paste 具体可以看那个 copy_paste的函数
