### ISSUE TITLE
Hand crafted transformation matrix A, in code

### ISSUE THREAD

**Issue by SumayyaInayat** [Hlings/AcroFOD#17]
Hi Hlings,
Hope you are doing good.
Can you please direct me to the code snippet where matrix A is defined because I am not able to find it.
Thanks!

**Comment by gaoypeng** [comment]
Hi, I unified the augmentation techniques into defining a hand-crafted matrix A for writing. It means different types of augmentation. Please refer [here](https://github.com/Hlings/AcroFOD/issues/15#issuecomment-1779993431) for more related codes. Feel free to reach out to me if any further questions :)
