### ISSUE TITLE
city_and_foggy8_3.yaml没有

### ISSUE THREAD

**Issue by 2640888968** [Hlings/AcroFOD#21]
Traceback (most recent call last):
  File "train_MMD.py", line 556, in <module>
    opt.data, opt.cfg, opt.hyp = check_file(opt.data), check_file(opt.cfg), check_file(opt.hyp)  # check files
  File "/DATA1/xds/few/utils/general.py", line 70, in check_file
    assert len(files), 'File Not Found: %s' % file  # assert file was found
AssertionError: File Not Found: ./data/city_and_foggy8_3.yaml
你好，请问下命令怎么是8_3，但你上传的代码只有8_1.yaml，该怎么解决呢

**Comment by gaoypeng** [comment]
Hi 感谢提醒！可以把命令里面的8_3改成8_1，我也同时在readme中把这个改了一下。

**Comment by 2640888968** [comment]
> Hi感谢提醒！可以把命令里面的8_3改成8_1，我也同时在readme中把这个改一下。

嗯呢，谢谢回复，已经成功解决了。
