### ISSUE TITLE
S->C cross-domain few-shot

### ISSUE THREAD

**Issue by TanFengji** [Hlings/AcroFOD#7]
Hi, for the S->C scenario, I made the following changes to city_and_foggy8_1.yaml

train_source: [C:\VOC2012\images, C:\cityscapes\images\train]
train_target: C:\VOC2012\images

val: C:\cityscapes\images\val

However, there are around 3k images from cityscapes train folder, how is this a few shot problem? Should I only select 8-10 images from cityscapes and put it under the train folder?

Thank you.

**Comment by gaoypeng** [comment]
Yes. You should select 8-10 images from the  C:\cityscapes\images\train folder (e.g., result in C:\cityscapes\images_mini\train). The codebase doesn't support automatically picking few-shot samples. You can also make your modification.
