### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ZhaoPo** [Hlings/AcroFOD#8]
Hello, may I ask how to use box-level (copy_pastev3.py) in the training process (train_MMD.py)? I see that there is no such part in the training code?

**Comment by TanFengji** [comment]
When the dataloader is created, a load_mosaic function is called. 

https://github.com/Hlings/AcroFOD/blob/53445c4f0ca7522cd55a8f9d420d9b452f0be44d/utils/datasets.py#L506

The function is exactly the same as the original yolo v5, but they replaced the yolo copy_paste with their own copy_paste function.

**Comment by gaoypeng** [comment]
Yes. I integrate the copy-paste augmentation into the "load_mosaic" function. The advanced version of yolov5 includes copy_paste augmentation, while the 3.0 version used in this repository does not have such augmentation yet. I am not sure which one can get better results. You can try them :).
